local hl

local function build(palette, roles)
  return {
    ['SpecialKey'] = { link = 'NonText' },
    ['EndOfBuffer'] = { fg = palette.base1 },
    ['TermCursor'] = { reverse = true },
    ['NonText'] = { fg = palette.base3 },
    ['Directory'] = { fg = palette.blue1 },
    ['ErrorMsg'] = { fg = palette.red1 },
    ['IncSearch'] = { fg = palette.base1, bg = palette.green1 },
    ['Search'] = { fg = palette.text1, bg = palette.base4 },
    ['CurSearch'] = { link = 'IncSearch' },
    ['MoreMsg'] = { fg = palette.blue1, bold = true },
    ['ModeMsg'] = { fg = palette.yellow1, bold = true },
    ['LineNr'] = { fg = palette.subtext1 },
    ['LineNrAbove'] = { link = 'LineNr' },
    ['LineNrBelow'] = { link = 'LineNr' },
    ['CursorLineNr'] = { fg = palette.text2 },
    ['CursorLineSign'] = { link = 'SignColumn' },
    ['CursorLineFold'] = { link = 'FoldColumn' },
    ['Question'] = { link = 'MoreMsg' },
    ['StatusLine'] = { fg = palette.text2, bg = palette.base0 },
    ['StatusLineNC'] = { fg = palette.subtext1, bg = palette.base0 },
    ['WinSeparator'] = { fg = palette.base0 },
    ['VertSplit'] = { link = 'WinSeparator' },
    ['Title'] = { fg = palette.cyan1, bold = true },
    ['Visual'] = { bg = palette.base3 },
    ['VisualNC'] = {},
    ['WarningMsg'] = { fg = palette.yellow1 },
    ['WildMenu'] = { link = 'Pmenu' },
    ['Folded'] = { bg = palette.base1 },
    ['FoldColumn'] = { fg = palette.subtext1 },
    ['DiffAdd'] = { bg = palette.green4 },
    ['DiffChange'] = { bg = palette.blue4 },
    ['DiffDelete'] = { bg = palette.red4 },
    ['DiffText'] = { bg = palette.blue3 },
    ['SignColumn'] = { fg = palette.subtext1 },
    ['Conceal'] = { fg = palette.base3 },
    ['SpellBad'] = { sp = palette.red1, undercurl = true },
    ['SpellCap'] = { sp = palette.yellow1, undercurl = true },
    ['SpellRare'] = { sp = palette.blue1, undercurl = true },
    ['SpellLocal'] = { sp = palette.blue1, undercurl = true },
    ['Pmenu'] = { fg = palette.text1, bg = palette.base3 },
    ['PmenuSel'] = { bg = palette.base4, bold = true },
    ['PmenuMatch'] = hl(roles.overprint),
    ['PmenuKind'] = { link = 'Pmenu' },
    ['PmenuKindSel'] = { link = 'PmenuSel' },
    ['PmenuExtra'] = { link = 'Pmenu' },
    ['PmenuExtraSel'] = { link = 'PmenuSel' },
    ['PmenuSbar'] = { link = 'Pmenu' },
    ['PmenuThumb'] = { bg = palette.subtext1 },
    ['TabLine'] = { fg = palette.text2, bg = palette.base2 },
    ['TabLineSel'] = { fg = palette.base1, bg = palette.subtext1 },
    ['TabLineFill'] = { bg = palette.base0 },
    ['CursorColumn'] = { link = 'CursorLine' },
    ['CursorLine'] = { bg = palette.base2 },
    ['ColorColumn'] = { bg = palette.base2 },
    ['QuickFixLine'] = { link = 'CursorLine' },
    ['Whitespace'] = { fg = palette.subtext1 },
    ['NormalNC'] = { fg = palette.text1, bg = palette.base1 },
    ['MsgSeparator'] = { link = 'StatusLine' },
    ['NormalFloat'] = { fg = palette.text1, bg = palette.base0 },
    ['MsgArea'] = {},
    ['FloatBorder'] = { fg = palette.base0, bg = palette.base0 },
    ['WinBar'] = { fg = palette.subtext1, bg = palette.base1, bold = true },
    ['WinBarNC'] = { fg = palette.subtext1, bg = palette.base1, bold = true },
    ['Cursor'] = { fg = palette.base1, bg = palette.text1 },
    ['FloatTitle'] = { fg = palette.subtext1, bg = palette.base0 },
    ['FloatFooter'] = { link = 'FloatTitle' },
    ['StatusLineTerm'] = { link = 'StatusLine' },
    ['StatusLineTermNC'] = { link = 'StatusLineNC' },
    ['RedrawDebugNormal'] = { reverse = true },
    ['Underlined'] = { underline = true },
    ['lCursor'] = { link = 'Cursor' },
    ['CursorIM'] = { link = 'Cursor' },
    ['ComplMatchIns'] = {},
    ['Substitute'] = { fg = palette.base1, bg = palette.red1 },
    ['VisualNOS'] = { link = 'Visual' },
    ['Normal'] = { fg = palette.text1, bg = palette.base1 },
    ['Character'] = { link = 'String' },
    ['Constant'] = hl(roles.constant),
    ['Number'] = hl(roles.number),
    ['Boolean'] = hl(roles.boolean),
    ['Float'] = { link = 'Number' },
    ['Conditional'] = hl(roles.conditional),
    ['Statement'] = hl(roles.keyword),
    ['Repeat'] = { link = 'Conditional' },
    ['Label'] = { link = 'Conditional' },
    ['Keyword'] = hl(roles.keyword),
    ['Exception'] = { link = 'Keyword' },
    ['Include'] = hl(roles.include),
    ['PreProc'] = hl(roles.preproc),
    ['Define'] = { link = 'PreProc' },
    ['Macro'] = { link = 'PreProc' },
    ['PreCondit'] = { link = 'PreProc' },
    ['StorageClass'] = { link = 'Type' },
    ['Type'] = hl(roles.type),
    ['Structure'] = { link = 'Type' },
    ['Typedef'] = { link = 'Type' },
    ['Tag'] = hl(roles.reference),
    ['Special'] = hl(roles.special),
    ['SpecialChar'] = { link = 'Special' },
    ['SpecialComment'] = { link = 'Special' },
    ['Debug'] = { link = 'Special' },
    ['Ignore'] = { link = 'Normal' },
    ['LspCodeLens'] = { fg = palette.subtext1 },
    ['LspCodeLensSeparator'] = { fg = palette.subtext1 },
    ['LspInlayHint'] = { fg = palette.subtext1, bg = palette.base2 },
    ['LspReferenceRead'] = { bg = palette.base2 },
    ['LspReferenceText'] = { bg = palette.base2 },
    ['LspReferenceWrite'] = { bg = palette.base2 },
    ['LspReferenceTarget'] = { link = 'LspReferenceText' },
    ['LspSignatureActiveParameter'] = { fg = palette.base3 },
    ['SnippetTabstop'] = { link = 'Visual' },
    ['DiagnosticFloatingError'] = { link = 'DiagnosticError' },
    ['DiagnosticError'] = { fg = palette.red1 },
    ['DiagnosticFloatingWarn'] = { link = 'DiagnosticWarn' },
    ['DiagnosticWarn'] = { fg = palette.yellow1 },
    ['DiagnosticFloatingInfo'] = { link = 'DiagnosticInfo' },
    ['DiagnosticInfo'] = { fg = palette.blue1 },
    ['DiagnosticFloatingHint'] = { link = 'DiagnosticHint' },
    ['DiagnosticHint'] = { fg = palette.cyan1 },
    ['DiagnosticFloatingOk'] = { link = 'DiagnosticOk' },
    ['DiagnosticOk'] = { fg = palette.green1 },
    ['DiagnosticVirtualTextError'] = { fg = palette.red1, bg = palette.red4 },
    ['DiagnosticVirtualTextWarn'] = { fg = palette.yellow1, bg = palette.yellow4 },
    ['DiagnosticVirtualTextInfo'] = { fg = palette.blue1, bg = palette.blue4 },
    ['DiagnosticVirtualTextHint'] = { fg = palette.cyan1, bg = palette.cyan4 },
    ['DiagnosticVirtualTextOk'] = { fg = palette.green1, bg = palette.green4 },
    ['DiagnosticVirtualLinesError'] = { link = 'DiagnosticError' },
    ['DiagnosticVirtualLinesWarn'] = { link = 'DiagnosticWarn' },
    ['DiagnosticVirtualLinesInfo'] = { link = 'DiagnosticInfo' },
    ['DiagnosticVirtualLinesHint'] = { link = 'DiagnosticHint' },
    ['DiagnosticVirtualLinesOk'] = { link = 'DiagnosticOk' },
    ['DiagnosticSignError'] = { link = 'DiagnosticError' },
    ['DiagnosticSignWarn'] = { link = 'DiagnosticWarn' },
    ['DiagnosticSignInfo'] = { link = 'DiagnosticInfo' },
    ['DiagnosticSignHint'] = { link = 'DiagnosticHint' },
    ['DiagnosticSignOk'] = { link = 'DiagnosticOk' },
    ['DiagnosticUnnecessary'] = { link = 'Comment' },
    ['DiagnosticDeprecated'] = { strikethrough = true },
    ['DiagnosticUnderlineError'] = { sp = palette.red1, undercurl = true },
    ['DiagnosticUnderlineWarn'] = { sp = palette.yellow1, undercurl = true },
    ['DiagnosticUnderlineInfo'] = { sp = palette.blue1, undercurl = true },
    ['DiagnosticUnderlineHint'] = { sp = palette.cyan1, undercurl = true },
    ['DiagnosticUnderlineOk'] = { sp = palette.green1, undercurl = true },
    ['Comment'] = hl(roles.comment),
    ['@variable'] = hl(roles.variable),
    ['@variable.builtin'] = hl(roles.variable_builtin),
    ['@variable.parameter'] = hl(roles.parameter),
    ['@variable.parameter.builtin'] = { link = 'Special' },
    ['@variable.member'] = hl(roles.member),
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = hl(roles.constant_builtin),
    ['@constant.macro'] = { link = 'Macro' },
    ['@module'] = hl(roles.module),
    ['@module.builtin'] = { link = 'Special' },
    ['@label'] = { link = 'Label' },
    ['@label.json'] = hl(roles.label),
    ['@string'] = { link = 'String' },
    ['@string.regexp'] = hl(roles.string_regex),
    ['@string.special'] = { link = 'Special' },
    ['@string.escape'] = hl(roles.string_escape, { bold = true }),
    ['@string.special.url'] = hl(roles.string_url, { italic = true, underline = true }),
    ['@string.regex'] = hl(roles.string_regex),
    ['String'] = hl(roles.string),
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@boolean'] = { link = 'Boolean' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@type'] = hl(roles.type),
    ['@type.builtin'] = hl(roles.type_builtin),
    ['@type.definition'] = { link = 'Type' },
    ['@attribute'] = hl(roles.decorator),
    ['@attribute.builtin'] = { link = 'Special' },
    ['@property'] = hl(roles.member),
    ['Identifier'] = hl(roles.identifier),
    ['@function'] = { link = 'Function' },
    ['@function.method'] = { link = 'Function' },
    ['@function.call'] = hl(roles.func_call),
    ['@function.method.call'] = { link = '@function.call' },
    ['@function.builtin'] = hl(roles.func_builtin),
    ['@function.macro'] = hl(roles.func_macro),
    ['Function'] = hl(roles.func),
    ['@constructor'] = hl(roles.constructor),
    ['@constructor.lua'] = hl(roles.punctuation),
    ['@operator'] = { link = 'Operator' },
    ['Operator'] = hl(roles.operator),
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.conditional.ternary'] = { link = 'Conditional' },
    ['@keyword.return'] = hl(roles.keyword_return),
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.storage'] = { link = 'StorageClass' },
    ['@keyword.import'] = { link = 'Include' },
    ['@keyword.operator'] = hl(roles.keyword_operator),
    ['@keyword.function'] = hl(roles.keyword),
    ['@keyword.coroutine'] = { link = 'Keyword' },
    ['@keyword.exception'] = { link = 'Exception' },
    ['@punctuation'] = hl(roles.punctuation),
    ['@punctuation.special'] = hl(roles.punctuation_special),
    ['@punctuation.bracket'] = hl(roles.punctuation),
    ['@punctuation.delimiter'] = hl(roles.punctuation),
    ['Delimiter'] = hl(roles.delimiter),
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { fg = palette.base1, bg = palette.red1 },
    ['@comment.warning'] = { fg = palette.base1, bg = palette.yellow1 },
    ['@comment.note'] = { fg = palette.base1, bg = palette.blue1 },
    ['@comment.todo'] = { fg = palette.base1, bg = palette.green1 },
    ['Todo'] = { link = '@comment.todo' },
    ['@markup'] = { fg = palette.text1 },
    ['@markup.strong'] = { bold = true },
    ['@markup.italic'] = { link = 'Italic' },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.underline'] = { link = 'Underline' },
    ['@markup.heading'] = { fg = palette.cyan1, bold = true },
    ['@markup.link'] = { fg = palette.magenta1, bold = true },
    ['@markup.heading.2.delimiter.vimdoc'] = { underline = true, nocombine = true },
    ['@markup.heading.1.delimiter.vimdoc'] = { underdouble = true, nocombine = true },
    ['@markup.heading.1.markdown'] = { link = '@markup.heading' },
    ['@markup.heading.6.markdown'] = { link = '@markup.heading' },
    ['@markup.heading.5.markdown'] = { link = '@markup.heading' },
    ['@markup.heading.4.markdown'] = { link = '@markup.heading' },
    ['@markup.heading.3.markdown'] = { link = '@markup.heading' },
    ['@markup.heading.2.markdown'] = { link = '@markup.heading' },
    ['@markup.math'] = { fg = palette.blue0 },
    ['@markup.quote'] = { fg = palette.text2 },
    ['@markup.raw'] = { fg = palette.red1 },
    ['@markup.list.checked'] = { fg = palette.green1 },
    ['@markup.list.unchecked'] = { fg = palette.yellow1 },
    ['@markup.link.label'] = { fg = palette.blue0 },
    ['@markup.raw.markdown_inline'] = { link = '@markup.raw' },
    ['@markup.strong.markdown_inline'] = { link = '@markup.strong' },
    ['@markup.link.url'] = { fg = palette.orange0, italic = true, underline = true },
    ['@markup.raw.block'] = { fg = palette.red1 },
    ['@diff'] = {},
    ['@diff.plus'] = { link = 'diffAdded' },
    ['@diff.minus'] = { link = 'diffRemoved' },
    ['@diff.delta'] = { link = 'diffChanged' },
    ['Added'] = { link = 'diffAdded' },
    ['Removed'] = { link = 'diffRemoved' },
    ['Changed'] = { link = 'diffChanged' },
    ['@tag'] = hl(roles.tag),
    ['@tag.builtin'] = { link = 'Special' },
    ['@tag.attribute'] = hl(roles.tag_attribute, { italic = true }),
    ['@tag.delimiter'] = hl(roles.tag_delimiter),
    ['@lsp'] = {},
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.comment'] = { link = '@comment' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.event'] = { link = '@type' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.interface'] = hl(roles.type),
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.macro'] = { link = '@constant.macro' },
    ['@lsp.type.method'] = { link = '@function.method' },
    ['@lsp.type.modifier'] = hl(roles.keyword),
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.type.parameter'] = { link = '@parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.regexp'] = { link = '@string.regexp' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type.definition' },
    ['@lsp.type.variable'] = {},
    ['@lsp.mod.deprecated'] = { link = 'DiagnosticDeprecated' },
    ['@lsp.typemod.variable.injected'] = { link = '@variable' },
    ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
    ['@lsp.typemod.type.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.string.injected'] = { link = '@string' },
    ['@lsp.typemod.operator.injected'] = { link = '@operator' },
    ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.macro.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.enumMember.defaultLibrary'] = { link = '@constant.builtin' },
    ['@lsp.typemod.enum.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.typemod.class.defaultLibrary'] = { link = '@type.builtin' },
    ['@lsp.type.unresolvedReference'] = { link = '@error' },
    ['@lsp.type.formatSpecifier'] = { link = '@punctuation.special' },
    ['@lsp.type.escapeSequence'] = { link = '@string.escape' },
    ['@lsp.type.boolean'] = { link = '@boolean' },
    ['@lsp.type.typeAlias'] = { link = '@type.definition' },
    ['@lsp.type.builtinType'] = { link = '@type.builtin' },
    ['@lsp.type.selfKeyword'] = { link = '@variable.builtin' },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.keyword.async'] = { link = '@keyword.coroutine' },
    ['@lsp.type.type.kotlin'] = {},
    ['@lsp.type.method.kotlin'] = {},
    ['@lsp.type.class.kotlin'] = {},
    ['FloatShadow'] = {},
    ['FloatShadowThrough'] = {},
    ['MatchParen'] = { fg = palette.text1, bold = true },
    ['RedrawDebugClear'] = {},
    ['RedrawDebugComposed'] = {},
    ['RedrawDebugRecompose'] = {},
    ['Error'] = { fg = palette.red1 },
    ['NvimInternalError'] = {},
    ['NvimAssignment'] = { link = 'Operator' },
    ['NvimPlainAssignment'] = { link = 'NvimAssignment' },
    ['NvimAugmentedAssignment'] = { link = 'NvimAssignment' },
    ['NvimAssignmentWithAddition'] = { link = 'NvimAugmentedAssignment' },
    ['NvimAssignmentWithSubtraction'] = { link = 'NvimAugmentedAssignment' },
    ['NvimAssignmentWithConcatenation'] = { link = 'NvimAugmentedAssignment' },
    ['NvimOperator'] = { link = 'Operator' },
    ['NvimUnaryOperator'] = { link = 'NvimOperator' },
    ['NvimUnaryPlus'] = { link = 'NvimUnaryOperator' },
    ['NvimUnaryMinus'] = { link = 'NvimUnaryOperator' },
    ['NvimNot'] = { link = 'NvimUnaryOperator' },
    ['NvimBinaryOperator'] = { link = 'NvimOperator' },
    ['NvimComparison'] = { link = 'NvimBinaryOperator' },
    ['NvimComparisonModifier'] = { link = 'NvimComparison' },
    ['NvimBinaryPlus'] = { link = 'NvimBinaryOperator' },
    ['NvimBinaryMinus'] = { link = 'NvimBinaryOperator' },
    ['NvimConcat'] = { link = 'NvimBinaryOperator' },
    ['NvimConcatOrSubscript'] = { link = 'NvimConcat' },
    ['NvimOr'] = { link = 'NvimBinaryOperator' },
    ['NvimAnd'] = { link = 'NvimBinaryOperator' },
    ['NvimMultiplication'] = { link = 'NvimBinaryOperator' },
    ['NvimDivision'] = { link = 'NvimBinaryOperator' },
    ['NvimMod'] = { link = 'NvimBinaryOperator' },
    ['NvimTernary'] = { link = 'NvimOperator' },
    ['NvimTernaryColon'] = { link = 'NvimTernary' },
    ['NvimParenthesis'] = { link = 'Delimiter' },
    ['NvimLambda'] = { link = 'NvimParenthesis' },
    ['NvimNestingParenthesis'] = { link = 'NvimParenthesis' },
    ['NvimCallingParenthesis'] = { link = 'NvimParenthesis' },
    ['NvimSubscript'] = { link = 'NvimParenthesis' },
    ['NvimSubscriptBracket'] = { link = 'NvimSubscript' },
    ['NvimSubscriptColon'] = { link = 'NvimSubscript' },
    ['NvimCurly'] = { link = 'NvimSubscript' },
    ['NvimContainer'] = { link = 'NvimParenthesis' },
    ['NvimDict'] = { link = 'NvimContainer' },
    ['NvimList'] = { link = 'NvimContainer' },
    ['NvimIdentifier'] = { link = 'Identifier' },
    ['NvimIdentifierScope'] = { link = 'NvimIdentifier' },
    ['NvimIdentifierScopeDelimiter'] = { link = 'NvimIdentifier' },
    ['NvimIdentifierName'] = { link = 'NvimIdentifier' },
    ['NvimIdentifierKey'] = { link = 'NvimIdentifier' },
    ['NvimColon'] = { link = 'Delimiter' },
    ['NvimComma'] = { link = 'Delimiter' },
    ['NvimArrow'] = { link = 'Delimiter' },
    ['NvimRegister'] = { link = 'SpecialChar' },
    ['NvimNumber'] = { link = 'Number' },
    ['NvimFloat'] = { link = 'NvimNumber' },
    ['NvimNumberPrefix'] = { link = 'Type' },
    ['NvimOptionSigil'] = { link = 'Type' },
    ['NvimOptionName'] = { link = 'NvimIdentifier' },
    ['NvimOptionScope'] = { link = 'NvimIdentifierScope' },
    ['NvimOptionScopeDelimiter'] = { link = 'NvimIdentifierScopeDelimiter' },
    ['NvimEnvironmentSigil'] = { link = 'NvimOptionSigil' },
    ['NvimEnvironmentName'] = { link = 'NvimIdentifier' },
    ['NvimString'] = { link = 'String' },
    ['NvimStringBody'] = { link = 'NvimString' },
    ['NvimStringQuote'] = { link = 'NvimString' },
    ['NvimStringSpecial'] = { link = 'SpecialChar' },
    ['NvimSingleQuote'] = { link = 'NvimStringQuote' },
    ['NvimSingleQuotedBody'] = { link = 'NvimStringBody' },
    ['NvimSingleQuotedQuote'] = { link = 'NvimStringSpecial' },
    ['NvimDoubleQuote'] = { link = 'NvimStringQuote' },
    ['NvimDoubleQuotedBody'] = { link = 'NvimStringBody' },
    ['NvimDoubleQuotedEscape'] = { link = 'NvimStringSpecial' },
    ['NvimFigureBrace'] = { link = 'NvimInternalError' },
    ['NvimSingleQuotedUnknownEscape'] = { link = 'NvimInternalError' },
    ['NvimSpacing'] = { link = 'Normal' },
    ['NvimInvalidSingleQuotedUnknownEscape'] = { link = 'NvimInternalError' },
    ['NvimInvalid'] = { link = 'Error' },
    ['NvimInvalidAssignment'] = { link = 'NvimInvalid' },
    ['NvimInvalidPlainAssignment'] = { link = 'NvimInvalidAssignment' },
    ['NvimInvalidAugmentedAssignment'] = { link = 'NvimInvalidAssignment' },
    ['NvimInvalidAssignmentWithAddition'] = { link = 'NvimInvalidAugmentedAssignment' },
    ['NvimInvalidAssignmentWithSubtraction'] = { link = 'NvimInvalidAugmentedAssignment' },
    ['NvimInvalidAssignmentWithConcatenation'] = { link = 'NvimInvalidAugmentedAssignment' },
    ['NvimInvalidOperator'] = { link = 'NvimInvalid' },
    ['NvimInvalidUnaryOperator'] = { link = 'NvimInvalidOperator' },
    ['NvimInvalidUnaryPlus'] = { link = 'NvimInvalidUnaryOperator' },
    ['NvimInvalidUnaryMinus'] = { link = 'NvimInvalidUnaryOperator' },
    ['NvimInvalidNot'] = { link = 'NvimInvalidUnaryOperator' },
    ['NvimInvalidBinaryOperator'] = { link = 'NvimInvalidOperator' },
    ['NvimInvalidComparison'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidComparisonModifier'] = { link = 'NvimInvalidComparison' },
    ['NvimInvalidBinaryPlus'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidBinaryMinus'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidConcat'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidConcatOrSubscript'] = { link = 'NvimInvalidConcat' },
    ['NvimInvalidOr'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidAnd'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidMultiplication'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidDivision'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidMod'] = { link = 'NvimInvalidBinaryOperator' },
    ['NvimInvalidTernary'] = { link = 'NvimInvalidOperator' },
    ['NvimInvalidTernaryColon'] = { link = 'NvimInvalidTernary' },
    ['NvimInvalidDelimiter'] = { link = 'NvimInvalid' },
    ['NvimInvalidParenthesis'] = { link = 'NvimInvalidDelimiter' },
    ['NvimInvalidLambda'] = { link = 'NvimInvalidParenthesis' },
    ['NvimInvalidNestingParenthesis'] = { link = 'NvimInvalidParenthesis' },
    ['NvimInvalidCallingParenthesis'] = { link = 'NvimInvalidParenthesis' },
    ['NvimInvalidSubscript'] = { link = 'NvimInvalidParenthesis' },
    ['NvimInvalidSubscriptBracket'] = { link = 'NvimInvalidSubscript' },
    ['NvimInvalidSubscriptColon'] = { link = 'NvimInvalidSubscript' },
    ['NvimInvalidCurly'] = { link = 'NvimInvalidSubscript' },
    ['NvimInvalidContainer'] = { link = 'NvimInvalidParenthesis' },
    ['NvimInvalidDict'] = { link = 'NvimInvalidContainer' },
    ['NvimInvalidList'] = { link = 'NvimInvalidContainer' },
    ['NvimInvalidValue'] = { link = 'NvimInvalid' },
    ['NvimInvalidIdentifier'] = { link = 'NvimInvalidValue' },
    ['NvimInvalidIdentifierScope'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidIdentifierScopeDelimiter'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidIdentifierName'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidIdentifierKey'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidColon'] = { link = 'NvimInvalidDelimiter' },
    ['NvimInvalidComma'] = { link = 'NvimInvalidDelimiter' },
    ['NvimInvalidArrow'] = { link = 'NvimInvalidDelimiter' },
    ['NvimInvalidRegister'] = { link = 'NvimInvalidValue' },
    ['NvimInvalidNumber'] = { link = 'NvimInvalidValue' },
    ['NvimInvalidFloat'] = { link = 'NvimInvalidNumber' },
    ['NvimInvalidNumberPrefix'] = { link = 'NvimInvalidNumber' },
    ['NvimInvalidOptionSigil'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidOptionName'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidOptionScope'] = { link = 'NvimInvalidIdentifierScope' },
    ['NvimInvalidOptionScopeDelimiter'] = { link = 'NvimInvalidIdentifierScopeDelimiter' },
    ['NvimInvalidEnvironmentSigil'] = { link = 'NvimInvalidOptionSigil' },
    ['NvimInvalidEnvironmentName'] = { link = 'NvimInvalidIdentifier' },
    ['NvimInvalidString'] = { link = 'NvimInvalidValue' },
    ['NvimInvalidStringBody'] = { link = 'NvimStringBody' },
    ['NvimInvalidStringQuote'] = { link = 'NvimInvalidString' },
    ['NvimInvalidStringSpecial'] = { link = 'NvimStringSpecial' },
    ['NvimInvalidSingleQuote'] = { link = 'NvimInvalidStringQuote' },
    ['NvimInvalidSingleQuotedBody'] = { link = 'NvimInvalidStringBody' },
    ['NvimInvalidSingleQuotedQuote'] = { link = 'NvimInvalidStringSpecial' },
    ['NvimInvalidDoubleQuote'] = { link = 'NvimInvalidStringQuote' },
    ['NvimInvalidDoubleQuotedBody'] = { link = 'NvimInvalidStringBody' },
    ['NvimInvalidDoubleQuotedEscape'] = { link = 'NvimInvalidStringSpecial' },
    ['NvimInvalidDoubleQuotedUnknownEscape'] = { link = 'NvimInvalidValue' },
    ['NvimInvalidFigureBrace'] = { link = 'NvimInvalidDelimiter' },
    ['NvimInvalidSpacing'] = { link = 'ErrorMsg' },
    ['NvimDoubleQuotedUnknownEscape'] = { link = 'NvimInvalidValue' },
    ['Bold'] = { bold = true },
    ['Italic'] = { italic = true },
    ['Underline'] = { underline = true },
    ['@text'] = { link = '@markup' },
    ['@text.title'] = { link = '@markup.heading' },
    ['@text.strong'] = { link = '@markup.strong' },
    ['@text.emphasis'] = { link = 'Italic' },
    ['@text.underline'] = { link = 'Underline' },
    ['@text.strike'] = { link = '@markup.strikethrough' },
    ['@text.literal'] = { link = '@markup.raw' },
    ['@text.math'] = { link = '@markup.math' },
    ['@text.reference'] = { link = '@markup.link' },
    ['@text.todo'] = { link = '@comment.todo' },
    ['@text.todo.checked'] = { link = '@markup.list.checked' },
    ['@text.todo.unchecked'] = { link = '@markup.list.unchecked' },
    ['@text.danger'] = { link = '@comment.error' },
    ['@text.note'] = { link = '@comment.note' },
    ['@text.warning'] = { link = '@comment.warning' },
    ['@text.diff.add'] = { link = 'diffAdded' },
    ['@text.diff.delete'] = { link = 'diffRemoved' },
    ['@parameter'] = hl(roles.parameter),
    ['@field'] = hl(roles.member),
    ['@field.rust'] = hl(roles.member),
    ['@namespace'] = hl(roles.module),
    ['@float'] = { link = 'Float' },
    ['@repeat'] = { link = 'Repeat' },
    ['@include'] = { link = 'Include' },
    ['@exception'] = { link = 'Exception' },
    ['@conditional'] = { link = 'Conditional' },
    ['@storageclass'] = { link = 'StorageClass' },
    ['@error'] = {},
    ['diffAdded'] = { fg = palette.green1 },
    ['diffChanged'] = { fg = palette.blue1 },
    ['diffRemoved'] = { fg = palette.red1 },
    ['diffFile'] = { link = 'Type' },
    ['diffNewFile'] = { link = 'diffFile' },
    ['diffOldFile'] = { link = 'diffFile' },
    ['diffIndexLine'] = { link = 'PreProc' },
    ['diffLine'] = { link = 'Statement' },
    ['SignColumnSB'] = { link = 'SignColumn' },
    ['qfFileName'] = { link = 'Directory' },
    ['qfLineNr'] = { link = 'LineNr' },
    ['LazyProp'] = { link = 'LineNr' },
    ['LazyDimmed'] = { link = 'LineNr' },
    ['LazyButtonActive'] = { link = 'TabLineSel' },
    ['typescriptParens'] = { fg = palette.text2 },
  }
end

function hl(role, extra)
  return vim.tbl_extend('force', {}, role or {}, extra or {})
end

return build
