
return {
  name = 'solarized',
  roles = function(p)
    return {
      comment = { fg = p.subtext1, italic = true },
      string = { fg = p.cyan1 },
      string_escape = { fg = p.red1 },
      string_regex = { fg = p.red1 },
      string_url = { fg = p.cyan1 },
      number = { fg = p.cyan1 },
      constant = { fg = p.cyan1 },
      constant_builtin = { fg = p.cyan1 },
      keyword = { fg = p.green1 },
      keyword_return = { fg = p.green1 },
      keyword_operator = { fg = p.green1 },
      conditional = { fg = p.green1 },
      preproc = { fg = p.orange1 },
      type = { fg = p.yellow1 },
      type_builtin = { fg = p.yellow1 },
      constructor = { fg = p.blue1 },
      identifier = { fg = p.blue1 },
      func = { fg = p.blue1 },
      func_builtin = { fg = p.blue1 },
      func_macro = { fg = p.orange1 },
      variable = { fg = p.text1 },
      variable_builtin = { fg = p.blue1 },
      parameter = { fg = p.text1 },
      member = { fg = p.blue1 },
      module = { fg = p.blue1 },
      operator = { fg = p.text1 },
      punctuation = { fg = p.text1 },
      punctuation_special = { fg = p.red1 },
      delimiter = { fg = p.text1 },
      special = { fg = p.red1 },
      label = { fg = p.green1 },
      tag = { fg = p.blue1, bold = true },
      tag_attribute = { fg = p.text2 },
      tag_delimiter = { fg = p.subtext1 },
      reference = { fg = p.blue1 },
    }
  end,
}
