return function(palette)
  return {
    BlinkCmpKindSnippet = { fg = palette.yellow1 },
    BlinkCmpKindOperator = { fg = palette.magenta1 },
    BlinkCmpKindVariable = { fg = palette.red1 },
    BlinkCmpKindField = { fg = palette.green1 },
    BlinkCmpKindEnumMember = { link = 'BlinkCmpKindField' },
    BlinkCmpKindTypeParameter = { link = 'Type' },
    BlinkCmpKindProperty = { link = '@property' },
    BlinkCmpKindModule = { link = '@namespace' },
    BlinkCmpKindStruct = { link = 'Type' },
    BlinkCmpKindClass = { link = 'Type' },
    BlinkCmpKindUnit = { link = 'Constant' },
    BlinkCmpKindEnum = { link = 'Constant' },
    BlinkCmpKindEvent = { link = 'Constant' },
    BlinkCmpKindInterface = { link = 'Type' },
    BlinkCmpKindConstructor = { link = 'Function' },
    BlinkCmpKindMethod = { link = 'Function' },
    BlinkCmpKindFunction = { link = 'Function' },
    BlinkCmpKindValue = { link = 'Keyword' },
    BlinkCmpKindReference = { link = 'Keyword' },
    BlinkCmpKindConstant = { link = '@constant' },
    BlinkCmpKindKeyword = { link = 'Keyword' },
    BlinkCmpKindDefault = { fg = palette.text2 },
    BlinkCmpLabel = { fg = palette.text1 },
    BlinkCmpLabelDetail = { fg = palette.subtext1 },
    BlinkCmpLabelMatch = { link = 'PmenuMatch' },
    BlinkCmpLabelDeprecated = { fg = palette.subtext1, strikethrough = true },
    BlinkCmpDocBorder = { fg = palette.base3, bg = palette.base0 },
    BlinkCmpDoc = { fg = palette.text1, bg = palette.base0 },
  }
end
