return function(palette)
  return {
    GitSignsAdd = { fg = palette.green2 },
    GitSignsChange = { fg = palette.blue2 },
    GitSignsDelete = { fg = palette.red2 },
    GitSignsChangedelete = { link = 'GitSignsChange' },
    GitSignsTopdelete = { link = 'GitSignsDelete' },
    GitSignsUntracked = { link = 'GitSignsAdd' },
    GitSignsAddNr = { link = 'GitSignsAdd' },
    GitSignsChangeNr = { link = 'GitSignsChange' },
    GitSignsDeleteNr = { link = 'GitSignsDelete' },
    GitSignsChangedeleteNr = { link = 'GitSignsChangeNr' },
    GitSignsTopdeleteNr = { link = 'GitSignsDeleteNr' },
    GitSignsUntrackedNr = { link = 'GitSignsAddNr' },
    GitSignsAddLn = { link = 'DiffAdd' },
    GitSignsChangeLn = { link = 'DiffChange' },
    GitSignsChangedeleteLn = { link = 'GitSignsChangeLn' },
    GitSignsTopdeleteLn = { link = 'GitSignsDeleteLn' },
    GitSignsDeleteLn = {},
    GitSignsUntrackedLn = { link = 'GitSignsAddLn' },
    GitSignsAddCul = { link = 'GitSignsAdd' },
    GitSignsChangeCul = { link = 'GitSignsChange' },
    GitSignsDeleteCul = { link = 'GitSignsDelete' },
    GitSignsChangedeleteCul = { link = 'GitSignsChangeCul' },
    GitSignsTopdeleteCul = { link = 'GitSignsDeleteCul' },
    GitSignsUntrackedCul = { link = 'GitSignsAddCul' },
    GitSignsStagedAdd = { fg = palette.green3 },
    GitSignsStagedChange = { fg = palette.blue3 },
    GitSignsStagedDelete = { fg = palette.red3 },
    GitSignsStagedChangedelete = { fg = palette.blue3 },
    GitSignsStagedTopdelete = { fg = palette.red3 },
    GitSignsStagedUntracked = { fg = palette.green3 },
    GitSignsStagedAddNr = { fg = palette.green3 },
    GitSignsStagedChangeNr = { fg = palette.blue3 },
    GitSignsStagedDeleteNr = { fg = palette.red3 },
    GitSignsStagedChangedeleteNr = { fg = palette.blue3 },
    GitSignsStagedTopdeleteNr = { fg = palette.red3 },
    GitSignsStagedUntrackedNr = { fg = palette.green3 },
    GitSignsStagedAddLn = { fg = palette.subtext1, bg = palette.green4 },
    GitSignsStagedChangeLn = { fg = palette.subtext1, bg = palette.blue4 },
    GitSignsStagedChangedeleteLn = { fg = palette.subtext1, bg = palette.blue4 },
    GitSignsStagedTopdeleteLn = {},
    GitSignsStagedUntrackedLn = { fg = palette.subtext1, bg = palette.green4 },
    GitSignsStagedAddCul = { fg = palette.green3 },
    GitSignsStagedChangeCul = { fg = palette.blue3 },
    GitSignsStagedDeleteCul = { fg = palette.red3 },
    GitSignsStagedChangedeleteCul = { fg = palette.blue3 },
    GitSignsStagedTopdeleteCul = { fg = palette.red3 },
    GitSignsStagedUntrackedCul = { fg = palette.green3 },
    GitSignsAddPreview = { link = 'DiffAdd' },
    GitSignsDeletePreview = { link = 'DiffDelete' },
    GitSignsCurrentLineBlame = { link = 'NonText' },
    GitSignsAddInline = { link = 'TermCursor' },
    GitSignsDeleteInline = { link = 'TermCursor' },
    GitSignsChangeInline = { link = 'TermCursor' },
    GitSignsAddLnInline = { link = 'GitSignsAddInline' },
    GitSignsChangeLnInline = { link = 'GitSignsChangeInline' },
    GitSignsDeleteLnInline = { link = 'GitSignsDeleteInline' },
    GitSignsDeleteVirtLn = { link = 'DiffDelete' },
    GitSignsDeleteVirtLnInLine = { link = 'GitSignsDeleteLnInline' },
    GitSignsVirtLnum = { link = 'GitSignsDeleteVirtLn' },
  }
end
