return function(palette)
  return {
    RenderMarkdownError = { link = 'DiagnosticError' },
    RenderMarkdownCodeInfo = { link = '@label' },
    RenderMarkdownQuote = { link = '@markup.quote' },
    RenderMarkdownQuote1 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownQuote2 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownQuote3 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownQuote4 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownQuote5 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownQuote6 = { link = 'RenderMarkdownQuote' },
    RenderMarkdownCode = { link = 'ColorColumn' },
    RenderMarkdownCodeBorder = { link = 'RenderMarkdownCode' },
    RenderMarkdownCodeFallback = { link = 'Normal' },
    RenderMarkdownCodeInline = { fg = palette.red1, bg = palette.base2, italic = false },
    RenderMarkdownInlineHighlight = { link = 'RenderMarkdownCodeInline' },
    RenderMarkdownH1 = { link = '@markup.heading.1.markdown' },
    RenderMarkdownH2 = { link = '@markup.heading.2.markdown' },
    RenderMarkdownH3 = { link = '@markup.heading.3.markdown' },
    RenderMarkdownH4 = { link = '@markup.heading.4.markdown' },
    RenderMarkdownH5 = { link = '@markup.heading.5.markdown' },
    RenderMarkdownH6 = { link = '@markup.heading.6.markdown' },
    RenderMarkdownH1Bg = { link = 'DiffText' },
    RenderMarkdownH2Bg = { link = 'DiffAdd' },
    RenderMarkdownH3Bg = { link = 'DiffChange' },
    RenderMarkdownH4Bg = { link = 'DiffDelete' },
    RenderMarkdownH5Bg = { link = 'Visual' },
    RenderMarkdownH6Bg = { link = 'CursorColumn' },
    RenderMarkdownMath = { link = '@markup.math' },
    RenderMarkdownSign = { link = 'SignColumn' },
    RenderMarkdownDash = { link = 'LineNr' },
    RenderMarkdownBullet = { link = 'Normal' },
    RenderMarkdownSuccess = { link = 'DiagnosticOk' },
    RenderMarkdownWarn = { link = 'DiagnosticWarn' },
    RenderMarkdownInfo = { link = 'DiagnosticInfo' },
    RenderMarkdownHint = { link = 'DiagnosticHint' },
    RenderMarkdownTableRow = { link = 'Normal' },
    RenderMarkdownTableHead = { link = '@markup.heading' },
    RenderMarkdownTodo = { link = '@markup.raw' },
    RenderMarkdownChecked = { link = '@markup.list.checked' },
    RenderMarkdownUnchecked = { link = '@markup.list.unchecked' },
    RenderMarkdownLink = { link = '@markup.link.label' },
    RenderMarkdownWikiLink = { link = 'RenderMarkdownLink' },
    RenderMarkdownLinkTitle = { link = '@markup.link' },
    RenderMarkdownHtmlComment = { link = '@comment' },
    RenderMarkdownIndent = { link = 'Whitespace' },
  }
end
